swagger: "2.0"
info:
  description: "The description for api."
  version: "1.0.0"
  title: "IM_Server"
host: "localhost:3000"
basePath: "/api"

tags:
  - name: "user"
    description: "Operations about user"
schemes:
  - "http"
paths:
  /user/login:
    post:
      tags:
        - "user"
      summary: "Sign in"
      description: "Sign in"
      operationId: "User sign in"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "user"
          description: "User sign in"
          schema:
            type: "object"
            properties:
              account:
                type: "string"
              pwd:
                type: "string"
      responses:
        200:
          description: "OK"
          schema:
            type: object
            properties:
              code:
                type: integer
              token:
                type: string
              data:
                description: "A User object"
                $ref: "#/definitions/User"
      # security:
      #   - userid: []
      #     token: []
securityDefinitions:
  userid:
    type: apiKey
    name: userid
    in: header
  token:
    type: apiKey
    name: token
    in: header
responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: "#/definitions/Error"
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: "#/definitions/Error"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      account:
        type: "string"
      avatar:
        type: "string"
      email:
        type: "string"
      regisTime:
        type: "string"
      updateTime:
        type: "string"
    xml:
      name: "User"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
    required:
      - code
      - message
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
